# Generated by Django 5.1.3 on 2024-11-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='password',
        ),
        migrations.RemoveField(
            model_name='onetimepassword',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='onetimepassword',
            name='username',
        ),
    ]
