# Generated by Django 5.1.3 on 2024-12-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_remove_onetimepassword_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onetimepassword',
            options={'verbose_name': 'رمز یکبار مصرف', 'verbose_name_plural': 'رمزهای یکبار مصرف'},
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='code',
            field=models.CharField(max_length=6, verbose_name='کد OTP'),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل کاربر'),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان انقضا'),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='status',
            field=models.CharField(choices=[('EXP', 'منقضی شده'), ('ACT', 'فعال')], default='ACT', max_length=3, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='token',
            field=models.CharField(max_length=250, unique=True, verbose_name='توکن'),
        ),
    ]
