# Generated by Django 5.1.3 on 2024-12-04 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'وبلاگ', 'verbose_name_plural': 'وبلاگ\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='blogsection',
            options={'verbose_name': 'بخش وبلاگ', 'verbose_name_plural': 'بخش\u200cهای وبلاگ'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blogs/main-images/', verbose_name='تصویر اصلی'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Blogs.blog', verbose_name='وبلاگ'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='محتوای بخش'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/section-images/', verbose_name='تصویر بخش'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان بخش'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='blogs/section-video/', verbose_name='ویدیو بخش'),
        ),
    ]
