# Import necessary modules from Django and Django REST Framework
from django.urls import path
from rest_framework.routers import DefaultRouter

# Import views from the current application
from . import views

# Define the application namespace for URL routing
app_name = "Users"

# Initialize an empty list to hold URL patterns
urlpatterns = [
    # Additional URL patterns can be added here if needed
]

# Create a DefaultRouter instance to automatically generate URL routes
router = DefaultRouter()

# Register the UserViewSet with the router, associating it with the 'users' URL prefix
# This will create routes for standard CRUD operations on user objects
router.register(r'', views.UserViewSet, basename='users')

# Extend the urlpatterns list with the routes generated by the router
urlpatterns += router.urls