# Generated by Django 5.1.3 on 2024-12-04 10:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='skils',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_stack',
            field=models.CharField(blank=True, choices=[('DES', 'Designer'), ('DEV', 'Developer'), ('MAN', 'Manager')], default='DEV', max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
                ('mastery', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skills', to='Profiles.employeeprofile')),
            ],
            options={
                'verbose_name': 'Employee Skill',
                'verbose_name_plural': 'Employee Skills',
            },
        ),
        migrations.CreateModel(
            name='SimpleUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/simple-user-profiles/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Customer_Profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simple User Profile',
                'verbose_name_plural': 'Simple User Profiles',
            },
        ),
        migrations.DeleteModel(
            name='CustomersProfile',
        ),
        migrations.DeleteModel(
            name='EmployeeSkils',
        ),
    ]
