# Generated by Django 5.1.3 on 2024-11-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='employee_stack',
            field=models.CharField(blank=True, choices=[('DES', 'Designer'), ('DEV', 'Developer'), ('MAN', 'Manager')], default='DEV', max_length=3, null=True),
        ),
    ]
