# Generated by Django 5.1.3 on 2024-12-03 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_employeeprofile_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/simple-user-profiles/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Customer_Profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simple User Profile',
                'verbose_name_plural': 'Simple User Profiles',
            },
        ),
        migrations.DeleteModel(
            name='CustomersProfile',
        ),
    ]
