# Generated by Django 5.1.3 on 2024-12-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('SMP', 'Simple User'), ('EMP', 'Employee'), ('ADM', 'Admin')], default='SMP', max_length=3),
        ),
    ]
