# Generated by Django 5.1.3 on 2024-12-29 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='Projects/Images/', verbose_name='تصویر')),
                ('url', models.URLField(blank=True, verbose_name='آدرس وب\u200cسایت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان به\u200cروزرسانی')),
                ('status', models.CharField(choices=[('In Progress', 'در حال پیشرفت'), ('Completed', 'تکمیل شده'), ('Pending', 'در انتظار'), ('Canceled', 'لغو شده')], default='Pending', max_length=20, verbose_name='وضعیت')),
                ('main_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Services.mainservices', verbose_name='سرویس اصلی')),
                ('sub_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Services.subservice', verbose_name='سرویس فرعی')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
            },
        ),
    ]
