# Generated by Django 5.1.3 on 2024-12-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default="slug", max_length=200),
            preserve_default=False,
        ),
    ]
